// Code generated from the /tmp/qbo-cap pass-3 capture corpus (gql_pass3.json). DO NOT EDIT.

package gql

// mutationInputs maps every captured mutation operation to its declared
// variable signature exactly as the SPA declares it (e.g.
// "$input: Commerce_ConsumeInventoryInput!").
//
// mutationRequiredVars lists, per mutation, the variables the CALLER must
// supply: those declared non-null (trailing !) with no default value in
// the signature. Omitting such a variable makes the request invalid
// GraphQL, so it is refused locally before any network attempt. Variables
// left out of this table are nullable and therefore omittable per spec.
var (
	mutationInputs = map[string]string{
		"ActivateProductEntities":                               "$entities: [InactivateEntity!]",
		"AssignAccountPurposeMappings":                          "$input: Accounting_AssignAccountPurposeMappingsInput!",
		"AssignCostGroupForVariants":                            "$input: AssignCostGroupInput!",
		"AssignDimensionsForProducts":                           "$input: AssignProductDimensionsInput!",
		"AssignUnitSetForProducts":                              "$input: AssignUnitSetInput!",
		"BankingDisconnectOlbAccounts":                          "$input: Banking_DisconnectOlbInput!",
		"BatchUpdateProducts":                                   "$products: [Commerce_BatchUpdateProductInput!]!",
		"BktsAssignInterCompanyAccountMappings":                 "$input: Accounting_AssignInterCompanyAccountMappingsInput!",
		"BktsReassignInterCompanyAccountMappings":               "$input: Accounting_ReassignInterCompanyAccountMappingsInput!",
		"BktsRemoveInterCompanyAccountMappings":                 "$input: Accounting_RemoveInterCompanyAccountMappingsInput!",
		"BulkUpdateCustomExtensionRecommendations":              "$sourceEntityType: AppFoundations_CustomExtensionRecommendationSourceEntity!, $input: [AppFoundations_CustomExtensionRecommendationUpdateInput!]!",
		"CancelReconcile__integration_banking_reconcile_ui_qbo": "$input_0: UpdateIntegration_ReconciliationInput!",
		"ClrTxnLine__integration_banking_reconcile_ui_qbo":      "$input_0: UpdateIntegration_ReconciliationInput!",
		"CommerceConsumeInventory":                              "$input: Commerce_ConsumeInventoryInput!",
		"CommerceGenerateSerialLotNumbers":                      "$input: Commerce_GenerateSerialLotNumbersInput!",
		"CommerceReceiveInventory":                              "$input: Commerce_ReceiveInventoryInput!",
		"CommerceUpdateConsumeInventory":                        "$input: Commerce_UpdateConsumeInventoryInput!",
		"CommerceUpdateReceiveInventory":                        "$input: Commerce_UpdateReceiveInventoryInput!",
		"CreateAccount":                                         "$input: Accounting_CreateAccountInput!",
		"CreateAccountV2":                                       "$input: Accounting_CreateAccountInputV2!",
		"CreateAgentBuilderDefinitionForDimension":              "$input: AgentStudio_CreateDefinitionInput!",
		"CreateAttachment":                                      "$input: QbAppFoundation_CreateAttachmentInput!",
		"CreateAttachment_qbo":                                  "$input: CreateAttachment_AttachmentInput!",
		"CreateBundle":                                          "$item: CreateBundleInput!",
		"CreateCostGroup":                                       "$input: ProjectManagement_CostGroupCreateInput!",
		"CreateCustomerType_qbo":                                "$input: CreateNetwork_CustomerTypeInput!",
		"CreateProduct":                                         "$item: CreateProductInput!",
		"CreateProjectSeries":                                   "$input: CreateWork_RecurringProjectInput!",
		"CreateProject_workflow":                                "$input: CreateWork_ProjectInput!",
		"CreateSalesOrder":                                      "$order: CreateSalesOrderInput!",
		"CreateTaxAdjustment":                                   "$input: IndirectTax_CreateAdjustmentInput!",
		"CreateTaxPayment":                                      "$input: IndirectTax_CreatePaymentInput!",
		"CreateTransactions_Transaction_qbo":                    "$input_0: CreateTransactions_TransactionInput!",
		"CustomFieldDefinitionCreateMutation":                   "$input_0: CustomFieldDefinitionMutationInput!",
		"DeleteAccountingAccountPurposeMapping":                 "$ids: [ID!]!",
		"DeleteSalesOrder":                                      "$id: ID!",
		"DeleteTaxAdjustment":                                   "$input: IndirectTax_DeleteAdjustmentInput!",
		"DismissItem":                                           "$input: GTD_DismissItemInput!",
		"EfileTaxReturn":                                        "$input: IndirectTax_UpdateReturnInput!",
		"FinishReconcile__integration_banking_reconcile_ui_qbo": "$input_0: UpdateIntegration_ReconciliationInput!",
		"IMMEDIATE_RECOGNIZE_SCHEDULE":                          "$sequence: Int!",
		"InactivateProductEntities":                             "$entities: [InactivateEntity!]",
		"LinkInvoiceToSalesOrder":                               "$invoiceId: ID!",
		"MergeAccount":                                          "$input: Accounting_MergeAccountsInput!",
		"OigqlAutoSaveNote":                                     "$input: DigitalHelp_AutoSaveCreateNoteInput!",
		"OigqlCreateAttachment":                                 "$input: DigitalHelp_CreateAttachmentInput!",
		"OigqlCreateAttachmentUpdateNote":                       "$input: DigitalHelp_CreateAttachmentUpdateNoteInput!",
		"OigqlCreateAttachmentWithNote":                         "$input: DigitalHelp_CreateAttachmentWithNoteInput!",
		"OigqlCreateNote":                                       "$input: DigitalHelp_CreateAttachmentWithNoteInput!",
		"OigqlDeleteAttachment":                                 "$input: DigitalHelp_DeleteAttachmentInput!",
		"OigqlDeleteNote":                                       "$input: DigitalHelp_DeleteNoteInput!",
		"OigqlUpdateNote":                                       "$input: DigitalHelp_UpdateNoteInput!",
		"QbAppFoundationDeleteAttachment":                       "$input: QbAppFoundation_DeleteAttachmentInput!",
		"ReassignAccountPurposeMappings":                        "$input: Accounting_ReassignAccountPurposeMappingsInput!",
		"RemoveAccountPurposeMappings":                          "$input: Accounting_RemoveAccountPurposeMappingsInput!",
		"RestoreItem":                                           "$input: GTD_RestoreItemInput!",
		"SendSalesOrderEmail":                                   "$email: SalesOrderEmailInput!",
		"StartReconcile__integration_banking_reconcile_ui_qbo":  "$input_0: UpdateIntegration_ReconciliationInput!",
		"TaskManagementProcessBatchPreferences":                 "$input: TaskManagement_ProcessBatchPreferencesInput!",
		"TaskManagementUpdateTemplate":                          "$input: TaskManagement_UpdateTemplateInput!",
		"TaskManagementUseTemplate":                             "$input: TaskManagement_UseTemplateInput!",
		"ToggleCostGroupDeletion":                               "$input: ProjectManagement_CostGroupToggleDeletionInput!",
		"UPDATE_RECOGNITION_FREQUENCY":                          "$updateRecognitionFrequencyInput: UpdateRecognitionFrequencyInput!",
		"UndoReconcile__integration_banking_reconcile_ui_qbo":   "$input_0: UpdateIntegration_ReconcileSessionInput!",
		"UpdateAccount":                                         "$input: Accounting_UpdateAccountInput!",
		"UpdateAccountV2":                                       "$input: Accounting_UpdateAccountInput!",
		"UpdateActionOnSalesOrder":                              "$action: SalesOrderActionType",
		"UpdateAgentBuilderDefinitionForDimension":              "$input: AgentStudio_UpdateDefinitionInput!",
		"UpdateAttachment":                                      "$input: QbAppFoundation_UpdateAttachmentInput!",
		"UpdateBundle":                                          "$item: UpdateBundleInput!",
		"UpdateCostGroup":                                       "$input: ProjectManagement_CostGroupUpdateInput!",
		"UpdateDeferredRecognitionScheduleOp":                   "$input: Accounting_UpdateDeferredRecognitionScheduleInput!",
		"UpdateFieldDefinitionCreateMutation":                   "$input_0: CustomFieldDefinitionMutationInput!",
		"UpdateItemStatus":                                      "$entities: [ProductInformationManagement_UpdateItemStatusInput!]",
		"UpdateNetworkType_qbo":                                 "$input: UpdateNetwork_CustomerTypeInput!",
		"UpdateProduct":                                         "$input: UpdateProductInput!",
		"UpdateProjectSeries_workflow":                          "$input: UpdateWork_RecurringProjectInput!",
		"UpdateProject_workflow":                                "$input: UpdateWork_ProjectInput!",
		"UpdateReconcile__integration_banking_reconcile_ui_qbo": "$input_0: UpdateIntegration_ReconciliationInput!",
		"UpdateSalesOrder":                                      "$order: UpdateSalesOrderInput!",
		"UpdateSettings":                                        "$updates: [UpdateQbAppFoundationQbSettingsInput!]!",
		"UpdateTransactions_Deposit_SalesOrder":                 "$input_0: UpdateTransactions_TransactionInput!",
		"UpdateTransactions_Transaction_qbo":                    "$input: UpdateTransactions_TransactionInput!",
		"UpdateVariants":                                        "$variant: [UpdateVariantInput!]!",
	}

	mutationRequiredVars = map[string][]string{
		"AssignAccountPurposeMappings":                          {"input"},
		"AssignCostGroupForVariants":                            {"input"},
		"AssignDimensionsForProducts":                           {"input"},
		"AssignUnitSetForProducts":                              {"input"},
		"BankingDisconnectOlbAccounts":                          {"input"},
		"BatchUpdateProducts":                                   {"products"},
		"BktsAssignInterCompanyAccountMappings":                 {"input"},
		"BktsReassignInterCompanyAccountMappings":               {"input"},
		"BktsRemoveInterCompanyAccountMappings":                 {"input"},
		"BulkUpdateCustomExtensionRecommendations":              {"sourceEntityType", "input"},
		"CancelReconcile__integration_banking_reconcile_ui_qbo": {"input_0"},
		"ClrTxnLine__integration_banking_reconcile_ui_qbo":      {"input_0"},
		"CommerceConsumeInventory":                              {"input"},
		"CommerceGenerateSerialLotNumbers":                      {"input"},
		"CommerceReceiveInventory":                              {"input"},
		"CommerceUpdateConsumeInventory":                        {"input"},
		"CommerceUpdateReceiveInventory":                        {"input"},
		"CreateAccount":                                         {"input"},
		"CreateAccountV2":                                       {"input"},
		"CreateAgentBuilderDefinitionForDimension":              {"input"},
		"CreateAttachment":                                      {"input"},
		"CreateAttachment_qbo":                                  {"input"},
		"CreateBundle":                                          {"item"},
		"CreateCostGroup":                                       {"input"},
		"CreateCustomerType_qbo":                                {"input"},
		"CreateProduct":                                         {"item"},
		"CreateProjectSeries":                                   {"input"},
		"CreateProject_workflow":                                {"input"},
		"CreateSalesOrder":                                      {"order"},
		"CreateTaxAdjustment":                                   {"input"},
		"CreateTaxPayment":                                      {"input"},
		"CreateTransactions_Transaction_qbo":                    {"input_0"},
		"CustomFieldDefinitionCreateMutation":                   {"input_0"},
		"DeleteAccountingAccountPurposeMapping":                 {"ids"},
		"DeleteSalesOrder":                                      {"id"},
		"DeleteTaxAdjustment":                                   {"input"},
		"DismissItem":                                           {"input"},
		"EfileTaxReturn":                                        {"input"},
		"FinishReconcile__integration_banking_reconcile_ui_qbo": {"input_0"},
		"IMMEDIATE_RECOGNIZE_SCHEDULE":                          {"sequence"},
		"LinkInvoiceToSalesOrder":                               {"invoiceId"},
		"MergeAccount":                                          {"input"},
		"OigqlAutoSaveNote":                                     {"input"},
		"OigqlCreateAttachment":                                 {"input"},
		"OigqlCreateAttachmentUpdateNote":                       {"input"},
		"OigqlCreateAttachmentWithNote":                         {"input"},
		"OigqlCreateNote":                                       {"input"},
		"OigqlDeleteAttachment":                                 {"input"},
		"OigqlDeleteNote":                                       {"input"},
		"OigqlUpdateNote":                                       {"input"},
		"QbAppFoundationDeleteAttachment":                       {"input"},
		"ReassignAccountPurposeMappings":                        {"input"},
		"RemoveAccountPurposeMappings":                          {"input"},
		"RestoreItem":                                           {"input"},
		"SendSalesOrderEmail":                                   {"email"},
		"StartReconcile__integration_banking_reconcile_ui_qbo":  {"input_0"},
		"TaskManagementProcessBatchPreferences":                 {"input"},
		"TaskManagementUpdateTemplate":                          {"input"},
		"TaskManagementUseTemplate":                             {"input"},
		"ToggleCostGroupDeletion":                               {"input"},
		"UPDATE_RECOGNITION_FREQUENCY":                          {"updateRecognitionFrequencyInput"},
		"UndoReconcile__integration_banking_reconcile_ui_qbo":   {"input_0"},
		"UpdateAccount":                                         {"input"},
		"UpdateAccountV2":                                       {"input"},
		"UpdateAgentBuilderDefinitionForDimension":              {"input"},
		"UpdateAttachment":                                      {"input"},
		"UpdateBundle":                                          {"item"},
		"UpdateCostGroup":                                       {"input"},
		"UpdateDeferredRecognitionScheduleOp":                   {"input"},
		"UpdateFieldDefinitionCreateMutation":                   {"input_0"},
		"UpdateNetworkType_qbo":                                 {"input"},
		"UpdateProduct":                                         {"input"},
		"UpdateProjectSeries_workflow":                          {"input"},
		"UpdateProject_workflow":                                {"input"},
		"UpdateReconcile__integration_banking_reconcile_ui_qbo": {"input_0"},
		"UpdateSalesOrder":                                      {"order"},
		"UpdateSettings":                                        {"updates"},
		"UpdateTransactions_Deposit_SalesOrder":                 {"input_0"},
		"UpdateTransactions_Transaction_qbo":                    {"input"},
		"UpdateVariants":                                        {"variant"},
	}
)
